language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: required

install: composer install

before_script:
  # navigate out of module directory to prevent blown stack by recursive module lookup
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod +x phpunit.phar
  - sudo mv phpunit.phar /usr/local/bin/phpunit
  - phpunit --version

  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - php composer.phar require satooshi/php-coveralls

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml --bootstrap tests/bootstrap.php tests

after_script:
  - php vendor/bin/coveralls -v